use crate::ir::{SchemaIR, TableIR};
use crate::{
    GeneratedFile, GeneratedOutput, GenerateOptions, RustGeneratorConfig, TypeRegistry,
};
use std::path::PathBuf;

use super::imports::build_imports_block_for_table;
use super::render::{generate_table, generate_table_bare};
use super::resolver::RustTypeResolver;

/// Generate Rust code from a [`SchemaIR`].
///
/// This is the single entry point for Rust code generation.
/// Returns structured output — the caller (typically the CLI) is responsible
/// for writing files.
pub fn generate(schema: &SchemaIR, options: &GenerateOptions) -> GeneratedOutput {
    let resolver = RustTypeResolver::new(options.rust.type_registry.clone());
    let mut files = Vec::new();

    // mod.rs
    files.push(GeneratedFile {
        path: "mod.rs".into(),
        content: build_mod_rs(schema, options),
        overwrite: true,
    });

    // enums.rs
    if !schema.enums.is_empty() {
        files.push(GeneratedFile {
            path: "enums.rs".into(),
            content: super::enums::generate_enum_defs(&schema.enums),
            overwrite: true,
        });
    }

    // One file per table
    for table in &schema.tables {
        let file_name = format!("{}.rs", table.name.replace('-', "_"));
        let content = generate_table(table, options, &resolver);
        let imports = build_imports_block_for_table(table, &options.rust.type_registry);
        let content = if imports.is_empty() {
            content
        } else {
            format!("{imports}\n{content}")
        };
        files.push(GeneratedFile {
            path: PathBuf::from(file_name),
            content,
            overwrite: true,
        });
    }

    GeneratedOutput { files }
}

/// Generate a Rust struct string for a single table (bare enum names).
///
/// This is a convenience wrapper for single-table output (e.g. `inspect` command).
/// Internally constructs a one-table SchemaIR and delegates to [`generate`].
pub fn generate_struct(table: &TableIR, options: &GenerateOptions) -> String {
    let resolver = RustTypeResolver::new(options.rust.type_registry.clone());
    generate_table_bare(table, options, &resolver)
}

fn build_mod_rs(schema: &SchemaIR, options: &GenerateOptions) -> String {
    let mut decls: Vec<String> = Vec::new();

    if !schema.enums.is_empty() {
        decls.push("enums".into());
    }

    for table in &schema.tables {
        decls.push(table.name.replace('-', "_"));
    }

    decls.sort();

    let mut out = format!(
        "// Generated by neutrino-schema — {} module\n\n",
        options.rust.module_name
    );
    for decl in &decls {
        out.push_str(&format!("pub mod {decl};\n"));
    }
    out
}

/// Convenience wrapper — equivalent to calling [`generate`] then
/// [`OutputWriter::write`](crate::OutputWriter).
///
/// Kept for backward compatibility. Prefer `generate()` + `OutputWriter::write()`
/// in new code.
pub fn generate_files(
    schema: &SchemaIR,
    config: &crate::config::GeneratorConfig,
) -> std::io::Result<()> {
    let options = GenerateOptions {
        render_mode: config.render_mode,
        rust: RustGeneratorConfig {
            module_name: config.module_name.clone(),
            derive_from_row: false,
            type_registry: TypeRegistry::default(),
        },
    };
    let output = generate(schema, &options);
    crate::OutputWriter::write(&output, &config.output_dir)
}

/// Like [`generate_files`] but accepts a custom [`TypeRegistry`].
pub fn generate_files_with_registry(
    schema: &SchemaIR,
    config: &crate::config::GeneratorConfig,
    registry: &TypeRegistry,
) -> std::io::Result<()> {
    let options = GenerateOptions {
        render_mode: config.render_mode,
        rust: RustGeneratorConfig {
            module_name: config.module_name.clone(),
            derive_from_row: false,
            type_registry: registry.clone(),
        },
    };
    let output = generate(schema, &options);
    crate::OutputWriter::write(&output, &config.output_dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FieldIR, RelationStrategy};
    use crate::types::DbType;
    use crate::RenderMode;

    fn simple_schema() -> SchemaIR {
        let tables = vec![TableIR {
            name: "users".into(),
            fields: vec![
                FieldIR {
                    name: "id".into(),
                    ty: DbType::Integer,
                    nullable: false,
                    raw_type: "INTEGER".into(),
                    default_value: None,
                    generated: false,
                    comment: None,
                },
                FieldIR {
                    name: "email".into(),
                    ty: DbType::String,
                    nullable: false,
                    raw_type: "VARCHAR".into(),
                    default_value: None,
                    generated: false,
                    comment: None,
                },
                FieldIR {
                    name: "bio".into(),
                    ty: DbType::String,
                    nullable: true,
                    raw_type: "TEXT".into(),
                    default_value: None,
                    generated: false,
                    comment: None,
                },
            ],
            constraints: vec![],
            comment: None,
            indexes: vec![],
        }];
        SchemaIR::from_tables(tables, RelationStrategy::Disabled)
    }

    #[test]
    fn generate_produces_correct_files() {
        let schema = simple_schema();
        let output = generate(&schema, &GenerateOptions::default());

        // mod.rs
        let mod_file = output.file("mod.rs").expect("mod.rs");
        assert!(mod_file.content.contains("pub mod users;"));

        // users.rs
        let users = output.file("users.rs").expect("users.rs");
        assert!(users.content.contains("pub struct Users"));
        assert!(users.content.contains("pub id: i32,"));
        assert!(users.content.contains("pub email: String,"));
        assert!(users.content.contains("pub bio: Option<String>,"));
    }

    #[test]
    fn generate_no_enums_when_empty() {
        let schema = simple_schema();
        let output = generate(&schema, &GenerateOptions::default());
        assert!(output.file("enums.rs").is_none());
    }

    #[test]
    fn generate_struct_works() {
        let table = &simple_schema().tables[0];
        let out = generate_struct(table, &GenerateOptions::default());
        assert!(out.contains("pub struct Users"));
        assert!(out.contains("pub id: i32,"));
    }

    #[test]
    fn generate_debug_comments() {
        let table = TableIR {
            name: "items".into(),
            fields: vec![
                FieldIR {
                    name: "id".into(),
                    ty: DbType::Integer,
                    nullable: false,
                    raw_type: "integer".into(),
                    default_value: None,
                    generated: false,
                    comment: Some("Primary key".into()),
                },
                FieldIR {
                    name: "label".into(),
                    ty: DbType::String,
                    nullable: true,
                    raw_type: "text".into(),
                    default_value: None,
                    generated: false,
                    comment: None,
                },
            ],
            constraints: vec![],
            comment: Some(" Represents an inventory item".into()),
            indexes: vec![],
        };
        let opts = GenerateOptions {
            render_mode: RenderMode::Debug,
            ..Default::default()
        };
        let out = generate_struct(&table, &opts);
        assert!(out.contains("// integer, NOT NULL"));
        assert!(out.contains("/// Primary key"));
        assert!(out.contains("/// Represents an inventory item"));
        assert!(out.contains("pub label: Option<String>, // text, NULL"));
        assert!(!out.contains("/// ///"), "no double doc-comment prefix");
    }

    #[test]
    fn derive_from_row_added_when_enabled() {
        let table = &simple_schema().tables[0];
        let opts = GenerateOptions {
            rust: RustGeneratorConfig {
                derive_from_row: true,
                ..Default::default()
            },
            ..Default::default()
        };
        let out = generate_struct(table, &opts);
        assert!(out.contains("#[derive(Debug, Clone, sqlx::FromRow)]"));
    }

    #[test]
    fn derive_from_row_omitted_when_disabled() {
        let table = &simple_schema().tables[0];
        let out = generate_struct(table, &GenerateOptions::default());
        assert!(out.contains("#[derive(Debug, Clone)]"));
        assert!(!out.contains("sqlx::FromRow"));
    }

    #[test]
    fn custom_type_registry_is_used() {
        use std::collections::HashMap;
        let mut overrides = HashMap::new();
        overrides.insert("Uuid".into(), "MyUuid".into());
        let registry = TypeRegistry::with_overrides(overrides);

        let table = TableIR {
            name: "items".into(),
            fields: vec![FieldIR {
                name: "id".into(),
                ty: DbType::Uuid,
                nullable: false,
                raw_type: "uuid".into(),
                default_value: None,
                generated: false,
                comment: None,
            }],
            constraints: vec![],
            comment: None,
            indexes: vec![],
        };

        let opts = GenerateOptions {
            rust: RustGeneratorConfig {
                type_registry: registry,
                ..Default::default()
            },
            ..Default::default()
        };
        let out = generate_struct(&table, &opts);
        assert!(out.contains("pub id: MyUuid,"));
    }

    #[test]
    fn mod_rs_is_deterministic() {
        let table_b = TableIR {
            name: "beta".into(),
            fields: vec![],
            constraints: vec![],
            comment: None,
            indexes: vec![],
        };
        let table_a = TableIR {
            name: "alpha".into(),
            fields: vec![],
            constraints: vec![],
            comment: None,
            indexes: vec![],
        };
        let schema = SchemaIR::from_tables(vec![table_b, table_a], RelationStrategy::Disabled);
        let output = generate(&schema, &GenerateOptions::default());
        let mod_rs = output.file("mod.rs").expect("mod.rs");
        // alpha must come before beta
        let alpha_pos = mod_rs.content.find("alpha").expect("alpha in mod.rs");
        let beta_pos = mod_rs.content.find("beta").expect("beta in mod.rs");
        assert!(alpha_pos < beta_pos, "mod.rs entries must be sorted");
    }
}
