-- ==============================================
-- Table users
-- Main users table with denormalized last login fields and soft delete
-- ==============================================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  first_name VARCHAR(100) NOT NULL DEFAULT '',
  last_name VARCHAR(100) NOT NULL DEFAULT '',
  email VARCHAR(100) NOT NULL,
  is_verified SMALLINT NOT NULL DEFAULT 0,
  email_verified_at TIMESTAMPTZ DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  user_type SMALLINT NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1,
  last_login_at TIMESTAMPTZ DEFAULT NULL,
  last_login_ip INET DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_email_active ON users(email, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_email ON users(email) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_deleted_at ON users(deleted_at);
CREATE INDEX IF NOT EXISTS idx_email_verified_at ON users(email_verified_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON users(public_id);

COMMENT ON TABLE users IS 'Main users table with denormalized last login fields and soft delete';
COMMENT ON COLUMN users.id IS 'Internal auto-incrementing ID';
COMMENT ON COLUMN users.public_id IS 'Public unique identifier (UUID v4)';
COMMENT ON COLUMN users.first_name IS 'User first name';
COMMENT ON COLUMN users.last_name IS 'User last name';
COMMENT ON COLUMN users.email IS 'User email address (must be unique)';
COMMENT ON COLUMN users.is_verified IS 'Account verification status (false for unverified accounts)';
COMMENT ON COLUMN users.email_verified_at IS 'Timestamp when email was verified (NULL if not verified)';
COMMENT ON COLUMN users.password IS 'Argon2 hashed password (NULL for OAuth-only users)';
COMMENT ON COLUMN users.remember_token IS 'Token for "remember me" functionality';
COMMENT ON COLUMN users.user_type IS 'User role: 0=regular user, 1=admin, 2=moderator, etc.';
COMMENT ON COLUMN users.is_active IS 'Account activation status (false for deactivated accounts)';
COMMENT ON COLUMN users.last_login_at IS 'Timestamp of most recent successful login';
COMMENT ON COLUMN users.last_login_ip IS 'IP address of most recent login';
COMMENT ON COLUMN users.created_at IS 'Timestamp when user account was created';
COMMENT ON COLUMN users.updated_at IS 'Timestamp when user record was last updated';
COMMENT ON COLUMN users.deleted_at IS 'Timestamp when account was soft-deleted (NULL if active)';
