-- ==============================================
-- Table user_roles
-- Many-to-many relationship between users and roles
-- ==============================================
CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  role_id SMALLINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_role ON user_roles(user_id, role_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON user_roles(public_id);

COMMENT ON TABLE user_roles IS 'Many-to-many relationship between users and roles';
