-- ==============================================
-- Table user_security_settings
-- Separate table for 2FA and account lockout status
-- ==============================================
CREATE TABLE IF NOT EXISTS user_security_settings (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  two_factor_enabled SMALLINT NOT NULL DEFAULT 0,
  two_factor_secret VARCHAR(255) DEFAULT NULL,
  two_factor_recovery_codes TEXT DEFAULT NULL,
  two_factor_confirmed_at TIMESTAMPTZ DEFAULT NULL,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ DEFAULT NULL,
  last_password_change TIMESTAMPTZ DEFAULT NULL,
  account_locked_until TIMESTAMPTZ DEFAULT NULL,
  lock_reason VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_security_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uk_user_id UNIQUE (user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON user_security_settings(public_id);
CREATE INDEX IF NOT EXISTS idx_two_factor_enabled ON user_security_settings(two_factor_enabled);
CREATE INDEX IF NOT EXISTS idx_locked_until ON user_security_settings(locked_until);
CREATE INDEX IF NOT EXISTS idx_account_locked_until ON user_security_settings(account_locked_until);

COMMENT ON TABLE user_security_settings IS 'Stores security-related settings for users including 2FA and account lockout status';
