-- ==============================================
-- Table user_trusted_devices
-- Optional table for users to remember and manage trusted devices
-- ==============================================
CREATE TABLE IF NOT EXISTS user_trusted_devices (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  device_id BYTEA NOT NULL,
  device_name VARCHAR(100) DEFAULT NULL,
  device_type VARCHAR(50) DEFAULT NULL,
  os VARCHAR(50) DEFAULT NULL,
  browser VARCHAR(100) DEFAULT NULL,
  last_used_at TIMESTAMPTZ DEFAULT NULL,
  expires_at TIMESTAMPTZ DEFAULT NULL,
  is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  deleted_by BIGINT DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_trusted_device_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_device ON user_trusted_devices(user_id, device_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON user_trusted_devices(public_id);
CREATE INDEX IF NOT EXISTS idx_user_active ON user_trusted_devices(user_id, is_revoked);
CREATE INDEX IF NOT EXISTS idx_expires ON user_trusted_devices(expires_at);
CREATE INDEX IF NOT EXISTS idx_device_id ON user_trusted_devices(device_id);
CREATE INDEX IF NOT EXISTS idx_trusted_device ON user_trusted_devices(user_id, device_id);

COMMENT ON TABLE user_trusted_devices IS 'Optional trusted devices for user accounts';
