-- ==============================================
-- Table user_sessions
-- User sessions table
-- Application-level sessions
-- ==============================================
CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  session_id BYTEA NOT NULL UNIQUE,
  device_id BYTEA DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  user_agent_hash BYTEA DEFAULT NULL,
  payload BYTEA NOT NULL,
  is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
  is_2fa_verified BOOLEAN NOT NULL DEFAULT FALSE,
  last_activity TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT NULL,
  revoked_at TIMESTAMPTZ DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_device FOREIGN KEY (user_id, device_id)
    REFERENCES user_trusted_devices(user_id, device_id)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON user_sessions(public_id);
CREATE INDEX IF NOT EXISTS idx_user_last_activity ON user_sessions(user_id, last_activity);
CREATE INDEX IF NOT EXISTS idx_user_active ON user_sessions(user_id, is_revoked, expires_at);
CREATE INDEX IF NOT EXISTS idx_expiring_sessions ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_device ON user_sessions(user_id, device_id);

COMMENT ON TABLE user_sessions IS 'Application-level user sessions';
