-- ==============================================
-- Table user_allowed_ips
-- Optional table for users to whitelist specific IPs, should be mandatory for privileged users
-- ==============================================
CREATE TABLE IF NOT EXISTS user_allowed_ips (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  ip_address INET NOT NULL,
  label VARCHAR(100) DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  deleted_by BIGINT DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_allowed_ip_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_ip ON user_allowed_ips(user_id, ip_address);
CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON user_allowed_ips(public_id);
CREATE INDEX IF NOT EXISTS idx_user_active ON user_allowed_ips(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_ip_address ON user_allowed_ips(ip_address);

COMMENT ON TABLE user_allowed_ips IS 'Optional IP whitelist for user accounts, should be mandatory for privileged users';
