-- ==============================================
-- Table oauth_clients
-- OAuth client applications
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_clients (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  secret BYTEA NOT NULL,
  secret_expires_at TIMESTAMPTZ DEFAULT NULL,
  provider VARCHAR(50) DEFAULT NULL,
  personal_access_client BOOLEAN NOT NULL DEFAULT FALSE,
  pkce_required BOOLEAN NOT NULL DEFAULT TRUE,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_client_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_clients(public_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON oauth_clients(user_id);

COMMENT ON TABLE oauth_clients IS 'OAuth clients, App-level (not user-specific)';
