-- ==============================================
-- Table oauth_client_redirect_uris
-- Permitted OAuth redirect URIs per client
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_client_redirect_uris (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  redirect_uri VARCHAR(2000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_uri_client FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_client_redirect ON oauth_client_redirect_uris(client_id, redirect_uri);
CREATE INDEX IF NOT EXISTS idx_client_id ON oauth_client_redirect_uris(client_id);

COMMENT ON TABLE oauth_client_redirect_uris IS 'Permitted OAuth redirect URIs per client';
