-- ==============================================
-- Table oauth_client_grants
-- OAuth client grant types
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_client_grants (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  client_id BIGINT NOT NULL,
  grant_type VARCHAR(20) NOT NULL CHECK (grant_type IN ('authorization_code', 'client_credentials', 'device_code', 'refresh_token')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ DEFAULT NULL,
  revocation_reason VARCHAR(255) DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_grant_client FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_client_grants(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_grant ON oauth_client_grants(client_id, grant_type);

COMMENT ON TABLE oauth_client_grants IS 'OAuth client grant types for client (excludes deprecated implicit/password grants)';
