-- ==============================================
-- Table oauth_providers
-- OAuth identity providers
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_providers (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  deleted_by BIGINT DEFAULT NULL,

  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_providers(public_id);

COMMENT ON TABLE oauth_providers IS 'OAuth identity providers';
