-- ==============================================
-- Table oauth_accounts
-- Links user accounts to OAuth providers
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_accounts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  provider_id BIGINT NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  access_token VARCHAR(512) DEFAULT NULL,
  refresh_token VARCHAR(512) DEFAULT NULL,
  token_expires_at TIMESTAMPTZ NOT NULL,
  token_issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  deleted_by BIGINT DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_oauth_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_oauth_provider FOREIGN KEY (provider_id) REFERENCES oauth_providers(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_accounts(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_provider_user ON oauth_accounts(provider_id, provider_user_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON oauth_accounts(user_id);

COMMENT ON TABLE oauth_accounts IS 'Links user accounts to OAuth providers (e.g., Google, GitHub). User-specific';
