-- ==============================================
-- Table oauth_access_tokens
-- OAuth access tokens for user and clients
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_access_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  token BYTEA NOT NULL,
  client_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  scopes VARCHAR(1000) DEFAULT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_token_client FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_access_tokens(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_token ON oauth_access_tokens(token);
CREATE INDEX IF NOT EXISTS idx_client_id ON oauth_access_tokens(client_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON oauth_access_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_expires_at ON oauth_access_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_revoked ON oauth_access_tokens(revoked);

COMMENT ON TABLE oauth_access_tokens IS 'OAuth access tokens for user and clients';
