-- ==============================================
-- Table oauth_refresh_tokens
-- OAuth refresh tokens linked to access tokens
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_refresh_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  token BYTEA NOT NULL,
  access_token_id BIGINT NOT NULL,
  previous_token_id BIGINT DEFAULT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_refresh_access_token FOREIGN KEY (access_token_id) REFERENCES oauth_access_tokens(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_refresh_tokens(public_id);
CREATE INDEX IF NOT EXISTS idx_access_token_id ON oauth_refresh_tokens(access_token_id);

COMMENT ON TABLE oauth_refresh_tokens IS 'OAuth refresh tokens linked to access tokens';
