-- ==============================================
-- Table oauth_authorization_codes
-- Temporary auth codes for OAuth PKCE flow
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_authorization_codes (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  code BYTEA NOT NULL,
  client_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  redirect_uri VARCHAR(2000) DEFAULT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  code_challenge VARCHAR(128) DEFAULT NULL,
  code_challenge_method VARCHAR(10) DEFAULT NULL CHECK (code_challenge_method IN ('plain', 'S256')),
  scope VARCHAR(1000) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  consumed BOOLEAN NOT NULL DEFAULT FALSE,

  PRIMARY KEY (id),
  CONSTRAINT fk_authcode_client FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_authcode_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_authorization_codes(public_id);
CREATE INDEX IF NOT EXISTS idx_client_id ON oauth_authorization_codes(client_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON oauth_authorization_codes(user_id);

COMMENT ON TABLE oauth_authorization_codes IS 'Temporary auth codes for OAuth PKCE flow';
