-- ==============================================
-- Table oauth_device_codes
-- Implements OAuth 2.0 Device Authorization Grant (RFC 8628)
-- ==============================================
CREATE TABLE IF NOT EXISTS oauth_device_codes (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  device_code VARCHAR(100) NOT NULL,
  user_code VARCHAR(50) NOT NULL,
  client_id BIGINT NOT NULL,
  user_id BIGINT DEFAULT NULL,
  scopes VARCHAR(1000) DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  device_name VARCHAR(255) DEFAULT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  last_poll TIMESTAMPTZ DEFAULT NULL,
  poll_interval INTEGER NOT NULL DEFAULT 5,
  status VARCHAR(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied', 'expired')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_at TIMESTAMPTZ DEFAULT NULL,
  denied_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_device_client FOREIGN KEY (client_id) REFERENCES oauth_clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON oauth_device_codes(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_device_code ON oauth_device_codes(device_code);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_code ON oauth_device_codes(user_code);
CREATE INDEX IF NOT EXISTS idx_client_id ON oauth_device_codes(client_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON oauth_device_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_status ON oauth_device_codes(status);
CREATE INDEX IF NOT EXISTS idx_expires_at ON oauth_device_codes(expires_at);

COMMENT ON TABLE oauth_device_codes IS 'Implements OAuth 2.0 Device Authorization Grant (RFC 8628)';
