-- ==============================================
-- Table personal_access_tokens
-- API tokens for user authentication
-- ==============================================
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  token BYTEA NOT NULL,
  abilities VARCHAR(1000) DEFAULT NULL,
  last_used_at TIMESTAMPTZ DEFAULT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  last_used_ip INET DEFAULT NULL,
  last_used_user_agent VARCHAR(255) DEFAULT NULL,
  revoked_at TIMESTAMPTZ DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_pat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON personal_access_tokens(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_token ON personal_access_tokens(token);
CREATE INDEX IF NOT EXISTS idx_user_id ON personal_access_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_expires_at ON personal_access_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_revoked ON personal_access_tokens(revoked);

COMMENT ON TABLE personal_access_tokens IS 'API tokens for user authentication';
