-- ==============================================
-- Table password_reset_tokens
-- Stores password reset tokens with expiration and usage tracking
-- ==============================================
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  token BYTEA NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON password_reset_tokens(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_user ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_expires ON password_reset_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_used ON password_reset_tokens(used_at);
CREATE INDEX IF NOT EXISTS idx_ip_created ON password_reset_tokens(ip_address, created_at);

COMMENT ON TABLE password_reset_tokens IS 'Stores password reset tokens with expiration and usage tracking';
