-- ==============================================
-- Table email_verification_tokens
-- Stores email verification tokens with expiration and rate limiting
-- ==============================================
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  token BYTEA NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  used_at TIMESTAMPTZ DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_verification_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON email_verification_tokens(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_token ON email_verification_tokens(token);
CREATE INDEX IF NOT EXISTS idx_user ON email_verification_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_expires ON email_verification_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_used ON email_verification_tokens(used_at);
CREATE INDEX IF NOT EXISTS idx_email_verification_rate_limit ON email_verification_tokens(ip_address, created_at);
CREATE INDEX IF NOT EXISTS idx_email_rate_limit ON email_verification_tokens(email, created_at);

COMMENT ON TABLE email_verification_tokens IS 'Stores email verification tokens with expiration and usage tracking';
