-- ==============================================
-- Table remember_me_tokens
-- Stores persistent login tokens for "Remember Me" functionality
-- ==============================================
CREATE TABLE IF NOT EXISTS remember_me_tokens (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  device_id BYTEA DEFAULT NULL,
  series BYTEA NOT NULL,
  token BYTEA NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  last_used TIMESTAMPTZ DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  network VARCHAR(100) DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_remember_me_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON remember_me_tokens(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_remember_me_series_token ON remember_me_tokens(series, token);
CREATE INDEX IF NOT EXISTS idx_remember_me_tokens_user ON remember_me_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_remember_me_tokens_series ON remember_me_tokens(series);
CREATE INDEX IF NOT EXISTS idx_remember_me_tokens_expiry ON remember_me_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_remember_me_tokens_device ON remember_me_tokens(device_id);

COMMENT ON TABLE remember_me_tokens IS 'Stores persistent login tokens for Remember Me functionality';
