-- ==============================================
-- Table security_events
-- Logs security relevant events for auditing
-- ==============================================
CREATE TABLE IF NOT EXISTS security_events (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT DEFAULT NULL,
  event_type VARCHAR(50) NOT NULL,
  ip_address INET DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  metadata JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_sec_event_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON security_events(public_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON security_events(user_id);
CREATE INDEX IF NOT EXISTS idx_event_type ON security_events(event_type);
CREATE INDEX IF NOT EXISTS idx_created_at ON security_events(created_at);

COMMENT ON TABLE security_events IS 'Logs security relevant events for auditing';
