-- ==============================================
-- Table login_attempts
-- Tracks failed and successful login attempts for security and rate limiting
-- ==============================================
CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  ip_address INET NOT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  successful BOOLEAN NOT NULL DEFAULT FALSE,
  failure_reason VARCHAR(100) DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_login_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON login_attempts(public_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON login_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_email ON login_attempts(email);
CREATE INDEX IF NOT EXISTS idx_ip ON login_attempts(ip_address);
CREATE INDEX IF NOT EXISTS idx_attempted_at ON login_attempts(attempted_at);

COMMENT ON TABLE login_attempts IS 'Tracks failed and successful login attempts for security and rate limiting';
