-- ==============================================
-- Table account_lockouts
-- Tracks temporary account lockouts due to too many failed attempts
-- ==============================================
CREATE TABLE IF NOT EXISTS account_lockouts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  ip_address INET NOT NULL,
  reason VARCHAR(100) NOT NULL,
  locked_until TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  unlocked_at TIMESTAMPTZ DEFAULT NULL,
  unlock_reason VARCHAR(100) DEFAULT NULL,
  unlocked_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  locked_by BIGINT DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_lockout_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_lockout_unlocked_by FOREIGN KEY (unlocked_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON account_lockouts(public_id);
CREATE INDEX IF NOT EXISTS idx_user_id ON account_lockouts(user_id);
CREATE INDEX IF NOT EXISTS idx_locked_until ON account_lockouts(locked_until);

COMMENT ON TABLE account_lockouts IS 'Tracks temporary account lockouts due to too many failed attempts';
