-- ==============================================
-- Table ip_rate_limits
-- Tracks rate limiting by IP address
-- ==============================================
CREATE TABLE IF NOT EXISTS ip_rate_limits (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  ip_address INET NOT NULL,
  endpoint VARCHAR(255) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 1,
  first_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  blocked_until TIMESTAMPTZ DEFAULT NULL,
  block_reason VARCHAR(100) DEFAULT NULL,

  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON ip_rate_limits(public_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ip_endpoint ON ip_rate_limits(ip_address, endpoint);
CREATE INDEX IF NOT EXISTS idx_ip_blocked_until ON ip_rate_limits(ip_address, blocked_until);
CREATE INDEX IF NOT EXISTS idx_last_attempt ON ip_rate_limits(last_attempt_at);

COMMENT ON TABLE ip_rate_limits IS 'Tracks rate limiting by IP address to prevent abuse';
