-- ==============================================
-- Table network_restrictions
-- Current active network restrictions
-- ==============================================
CREATE TABLE IF NOT EXISTS network_restrictions (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  role_id SMALLINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  ip_ranges JSONB NOT NULL,
  countries JSONB DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_by BIGINT DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,

  PRIMARY KEY (id),
  CONSTRAINT fk_network_restrictions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_network_restrictions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_network_restrictions_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_network_restrictions_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON network_restrictions(public_id);
CREATE INDEX IF NOT EXISTS idx_role_active ON network_restrictions(role_id, is_active);
CREATE INDEX IF NOT EXISTS idx_deleted_at ON network_restrictions(deleted_at);

COMMENT ON TABLE network_restrictions IS 'Enforces network-level security for privileged users';
