-- ==============================================
-- Table network_restrictions_history
-- Audit log of all changes to network_restrictions
-- ==============================================
CREATE TABLE IF NOT EXISTS network_restrictions_history (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  restriction_id BIGINT NOT NULL,
  action VARCHAR(10) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
  old_value JSONB DEFAULT NULL,
  new_value JSONB DEFAULT NULL,
  performed_by BIGINT DEFAULT NULL,
  performed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_history_restriction FOREIGN KEY (restriction_id) REFERENCES network_restrictions(id) ON DELETE CASCADE,
  CONSTRAINT fk_history_user FOREIGN KEY (performed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON network_restrictions_history(public_id);
CREATE INDEX IF NOT EXISTS idx_restriction_action_time ON network_restrictions_history(restriction_id, action, performed_at);

COMMENT ON TABLE network_restrictions_history IS 'Audit log of changes to network restrictions';
