-- ==============================================
-- Table two_factor_codes
-- Stores two-factor authentication codes for users
-- ==============================================
CREATE TABLE IF NOT EXISTS two_factor_codes (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  public_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL,
  code VARCHAR(100) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ DEFAULT NULL,
  ip_address INET DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_two_factor_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_id ON two_factor_codes(public_id);
CREATE INDEX IF NOT EXISTS idx_user_code ON two_factor_codes(user_id, code);
CREATE INDEX IF NOT EXISTS idx_expires ON two_factor_codes(expires_at);

COMMENT ON TABLE two_factor_codes IS 'Stores two-factor authentication codes with expiration and usage tracking';
