use crate::config::GeneratorConfig;
use crate::ir::{FieldIR, SchemaIR, TableIR};

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in s.chars() {
        if ch == '_' || ch == '-' {
            upper = true;
        } else if upper {
            out.push(ch.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Convert a `snake_case` table name to `PascalCase` for use as a Rust struct name.
///
/// # Examples
///
/// ```
/// use neutrino_schema::to_struct_name;
/// assert_eq!(to_struct_name("users"), "Users");
/// assert_eq!(to_struct_name("blog_posts"), "BlogPosts");
/// assert_eq!(to_struct_name("user_profile_data"), "UserProfileData");
/// ```
pub fn to_struct_name(table_name: &str) -> String {
    pascal_case(table_name)
}

/// Controls whether generated structs include debug annotations.
///
/// Used by [`generate_struct`] and [`generate_files`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderMode {
    /// Clean output — no comments on fields.
    Clean,
    /// Include `// RawType, NULL/NOT NULL` comments on each field.
    Debug,
}

fn render_field(f: &FieldIR, mode: RenderMode) -> String {
    let ty = crate::types::dbtype_to_rust(&f.ty, f.nullable);
    match mode {
        RenderMode::Clean => format!("    pub {}: {},\n", f.name, ty),
        RenderMode::Debug => {
            let null_label = if f.nullable { "NULL" } else { "NOT NULL" };
            format!("    pub {}: {}, // {}, {}\n", f.name, ty, f.raw_type, null_label)
        }
    }
}

/// Render a single [`TableIR`] as a Rust struct definition.
///
/// The struct is `#[derive(Debug, Clone)]` and all fields are `pub`.
/// When `mode` is [`RenderMode::Debug`], each field gets a comment with
/// its raw SQL type and nullability.
///
/// # Example
///
/// ```rust
/// use neutrino_schema::*;
///
/// let table = TableIR {
///     name: "users".into(),
///     fields: vec![FieldIR {
///         name: "email".into(),
///         ty: DbType::String,
///         nullable: false,
///         raw_type: "Varchar".into(),
///     }],
/// };
///
/// let out = generate_struct(&table, RenderMode::Clean);
/// assert!(out.contains("pub struct Users"));
/// assert!(out.contains("email: String"));
/// ```
pub fn generate_struct(table: &TableIR, mode: RenderMode) -> String {
    let mut out = String::new();
    let struct_name = to_struct_name(&table.name);

    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));

    for f in &table.fields {
        out.push_str(&render_field(f, mode));
    }

    out.push_str("}\n");
    out
}

/// Write generated Rust structs to disk.
///
/// Creates one `.rs` file per table in `config.output_dir`, named after the
/// table (e.g. `users.rs`), plus a `mod.rs` that declares each sub-module.
/// Creates the output directory if it does not exist.
///
/// # Errors
///
/// Returns `Err` if the output directory cannot be created, or if any file
/// cannot be written.
pub fn generate_files(schema: &SchemaIR, config: &GeneratorConfig) -> std::io::Result<()> {
    std::fs::create_dir_all(&config.output_dir)?;

    let mut mod_decls = Vec::new();

    for table in &schema.tables {
        let file_name = format!("{}.rs", table.name.replace('-', "_"));
        let content = generate_struct(table, config.render_mode);

        std::fs::write(config.output_dir.join(&file_name), content)?;
        mod_decls.push(table.name.replace('-', "_"));
    }

    let mut mod_rs = format!("// Generated by neutrino-schema — {} module\n\n", config.module_name);
    for decl in &mod_decls {
        mod_rs.push_str(&format!("pub mod {decl};\n"));
    }
    std::fs::write(config.output_dir.join("mod.rs"), mod_rs)?;

    Ok(())
}

